### PR TITLE
fix #1

### LINKED ISSUE #1: Finaly some cfonb from CIC
First of all thanks for this amazing package.

During parsing i encounter several issue parsing cfonb from CIC.

- empty line can occur
- some 01 lines can be ignored with pattern "** PAS DE MOUVEMENT CE JOUR **" and "------------------------------"

But the most annoying is that 05 line (OperationDetail) are on multi line.

Are you okay if i make a PR to fix this ? (knowing that you actually throw an Exception if multiple 05 line are found for the same 01 line)

Thanks in advance :)

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

File: src/Cfonb120Reader.php [hunk 1]
```diff
@@ -25,6 +25,10 @@ class Cfonb120Reader extends AbstractReader
 {
     /** @var Statement[] */
     private $statements = [];
+    private const IGNORE_LINES = [
```
Comment (guillaume-sainthillier) [inline src/Cfonb120Reader.php:28]: I'm note sure to give this package the responsibility of ignoring some lines. Is it really a bug for you?

File: src/Banking/Operation.php [hunk 2]
```diff
@@ -55,6 +55,9 @@ class Operation
     /** @var OperationDetail|null */
     private $details;
 
+    /** @var OperationDetail[] */
+    private $subDetails = [];
```
Comment (guillaume-sainthillier) [inline src/Banking/Operation.php:59]: I think your implementation is better than mine.
We should change the `$details` property to be an array, keep the `getDetails` method for BC reason, and just add an method like `getAllDetails` instead of adding `$subDetails` property.

WDYT?

**Review by guillaume-sainthillier — COMMENTED** [review]
Thanks for PR!

File: src/Cfonb120Reader.php (hunk 1 above)
Comment (fezfez) [reply src/Cfonb120Reader.php:28]: Yeah if this line are not ignored this will throw an exception.
But i understand that this implementation of ignored lines is very naive.
Like lineParse i could add a similar mechanism "LineParserIgnore" with same method `supports(string $content): bool`

WDYT ?

File: src/Banking/Operation.php (hunk 2 above)
Comment (fezfez) [reply src/Banking/Operation.php:59]: ok so if we dont want BC `getDetails` will return the first element :)

Comment (guillaume-sainthillier) [reply src/Banking/Operation.php:59]: Yes!

File: src/Cfonb120Reader.php (hunk 1 above)
Comment (guillaume-sainthillier) [reply src/Cfonb120Reader.php:28]: I've made some tests with your file.
I think your problem could be fixed by setting the `_unused_4 ` to `[self::ALL, 50]` instead of `[self::BLANK, 50]` in the `Line01Parser` class.

Comment (fezfez) [reply src/Cfonb120Reader.php:28]: with this diff


```diff
diff --git a/src/Cfonb120Reader.php b/src/Cfonb120Reader.php
index 8e3b04d..e97d89e 100644
--- a/src/Cfonb120Reader.php
+++ b/src/Cfonb120Reader.php
@@ -55,12 +55,12 @@ class Cfonb120Reader extends AbstractReader
         foreach ($lines as $line) {
             if (empty($line)) {
                 continue;
-            }
+            }/*
             foreach (self::IGNORE_LINES as $toIgnore) {
                 if (strpos(strtolower($line), strtolower($toIgnore))) {
                     continue 2;
                 }
-            }
+            }*/
 
             foreach ($this->parsers as $parser) {
                 if (!$parser->supports($line)) {
diff --git a/src/Parser/Cfonb120/Line01Parser.php b/src/Parser/Cfonb120/Line01Parser.php
index f2246c6..0dccbcb 100644
--- a/src/Parser/Cfonb120/Line01Parser.php
+++ b/src/Parser/Cfonb120/Line01Parser.php
@@ -28,7 +28,7 @@ class Line01Parser extends AbstractCfonb120Parser
             'account_nb' => [self::ALPHANUMERIC, 11],
             '_unused_3' => [self::BLANK, 2],
             'date' => [self::NUMERIC, 6],
-            '_unused_4' => [self::BLANK, 50],
+            '_unused_4' => [self::ALL, 50],
             'amount' => [self::AMOUNT, 14],
             '_unused_5' => [self::ALL, 16],
         ]);

```

test fail 

```console
) Siarhi\Cfonb\Tests\Cfonb120ReaderTest::testComplexTest
Silarhi\Cfonb\Exceptions\ParseException: Unable to find a parser for the line :
"0710278    02204EUR2 00020427603  240420        ------------------------------            0000005843530B                 "
``

Comment (guillaume-sainthillier) [reply src/Cfonb120Reader.php:28]: I see 121 chars on this line :-) I think you've added an extra whitespace by error during the copy/paste.

File: src/Banking/Operation.php (hunk 2 above)
Comment (fezfez) [reply src/Banking/Operation.php]: done

File: src/Cfonb120Reader.php (hunk 1 above)
Comment (fezfez) [reply src/Cfonb120Reader.php]: done and working :+1: good catch

**Review by guillaume-sainthillier — APPROVED** [review]
Thank you Stéphane

**Comment by fezfez** [comment]
Thanks for your reactivity !
